name: Compile-CI

on:
  push:
    branches: [ latest_branch ]
  pull_request:
    branches: [ latest_branch ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Compile
        run: |
            cd src
            g++ -o helper-test.o source.cpp

      - name: Helper-Compile
        run: |
            cd DotnetInstallHelper/src
            g++ -o helper-test.o source.cpp