name: Compile-CI

on:
  push:
    branches: [ latest_branch ]
  pull_request:
    branches: [ latest_branch ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - run: |
          cd src
          ls

      - name: Compile
        uses: qhy040404/BuildMySource@v2

      - name: Helper-Compile
        run: |
            cd DotnetInstallHelper/src
            g++ -o helper-test.o source.cpp